import os
# Force google-genai SDK to use Developer API instead of Vertex AI
os.environ['GOOGLE_GENAI_USE_VERTEXAI'] = 'false'

import time
from google import genai
from dotenv import load_dotenv

from src.logger import get_agent_logger

# Ensure environment variables are loaded
load_dotenv()
logger = get_agent_logger()

def _call_llm_with_fallback(client, model_name: str, contents: str) -> str:
    """Helper to call generate_content with retries and fallback to gemini-2.5-flash."""
    models_to_try = [model_name]
    if model_name != 'gemini-2.5-flash':
        models_to_try.append('gemini-2.5-flash')
        
    last_error = None
    for model in models_to_try:
        for attempt in range(3):
            try:
                logger.info(f"Generating content using {model} (attempt {attempt+1}/3)...")
                response = client.models.generate_content(
                    model=model,
                    contents=contents
                )
                return response.text
            except Exception as e:
                last_error = e
                logger.warning(f"Error generating content with {model} on attempt {attempt+1}: {e}")
                if attempt < 2:
                    time.sleep(2 ** attempt)  # Exponential backoff: 1s, 2s
        logger.error(f"All attempts failed with model {model}. Trying fallback/next model if available.")
    
    raise last_error

def generate_cad_code(prompt: str, model_name: str = 'gemini-2.5-flash') -> str:
    """Generates CadQuery Python code from a natural language prompt."""
    from google.adk.agents.llm_agent import Agent
    from google.adk.runners import Runner
    from google.adk.sessions import DatabaseSessionService
    from google.genai import types
    import uuid
    import asyncio
    
    logger.info("Initializing ADK Runner for planner_agent...")
    
    system_prompt = """
You are an expert CAD engineer and Python developer. Your task is to generate strict CadQuery Python code based on the user's request.

RULES:
You must output ONLY valid Python code. No markdown formatting, no conversational filler, no explanations.
The code must instantiate a CadQuery solid and assign it to a variable named result_solid.
Use standard CadQuery syntax (e.g., import cadquery as cq).
Always import `math` explicitly if your code uses any mathematical operations (e.g. `math.sin`, `math.cos`, `math.pi`).
Ensure dimensions are in millimeters.
CRITICAL: Do NOT hallucinate or invent CadQuery selectors (e.g., do not use `LargestAreaSelector` or custom selectors). Stick strictly to standard string selectors like `>Z`, `<Z`, `>X`, `not >Z`, `%Plane`, or use direct geometric operations.
"""

    coder_agent = Agent(
        model=model_name,
        name='planner_agent',
        description='Expert CAD engineer and Python developer.',
        instruction=system_prompt,
    )
    
    db_dir = "outputs"
    os.makedirs(db_dir, exist_ok=True)
    db_path = os.path.join(db_dir, "adk_sessions.db")
    db_url = f"sqlite:///{os.path.abspath(db_path)}"
    
    session_service = DatabaseSessionService(db_url=db_url)
    session_id = str(uuid.uuid4())
    
    async def create_session():
        await session_service.create_session(
            app_name="planner_agent",
            user_id="user",
            session_id=session_id
        )
    asyncio.run(create_session())
    
    runner = Runner(
        agent=coder_agent,
        app_name="planner_agent",
        session_service=session_service
    )
    
    content = types.Content(role='user', parts=[types.Part(text=f"Request:{prompt}")])
    events = list(runner.run(user_id="user", session_id=session_id, new_message=content))
    
    response_text = ""
    for event in events:
        if event.is_final_response() and event.content and event.content.parts:
            response_text = event.content.parts[0].text
            break
            
    if not response_text:
        raise RuntimeError("No response text generated by planner_agent.")
    
    # Strip any potential markdown formatting from the response
    code = response_text.replace('```python', '').replace('```', '').strip()
    return code

def extract_expected_dimensions(prompt: str, model_name: str = 'gemini-2.5-flash') -> dict:
    """Uses the LLM to dynamically predict the expected bounding box of the object based on the prompt."""
    logger.info("Dynamically calculating expected dimensions from prompt...")
    api_key = os.environ.get("GEMINI_API_KEY")
    client = genai.Client(api_key=api_key)
    
    system_prompt = """
You are a geometry analysis agent. Based on the user's CAD prompt, calculate the expected bounding box dimensions (X, Y, Z in millimeters).
Return ONLY a valid JSON object in this exact format, with no markdown formatting:
{
    "x_mm": float,
    "y_mm": float,
    "z_mm": float,
    "tolerance_mm": float
}
Set the tolerance based on how complex/curved the object is (e.g., 1.0 for simple boxes, 5.0-10.0 for complex radial/curved objects).
"""
    full_prompt = f"{system_prompt}\nRequest:{prompt}"
    
    try:
        response_text = _call_llm_with_fallback(client, model_name, full_prompt)
        import json
        clean_text = response_text.replace('```json', '').replace('```', '').strip()
        dims = json.loads(clean_text)
        logger.info(f"Dynamically calculated dimensions: {dims}")
        return dims
    except Exception as e:
        logger.error(f"Failed to extract dimensions dynamically: {e}")
        # Fallback dimensions if extraction fails
        return {"x_mm": 100.0, "y_mm": 100.0, "z_mm": 100.0, "tolerance_mm": 10.0}
